### ISSUE TITLE
Hello,when I run the programme,A error ocur like this,I don't know where to get object-explorer.jar,please help me,thank you .

### ISSUE THREAD

**Issue by iechenyb** [shrekwang/object-inspector#1]
Exception in thread "main" java.lang.ExceptionInInitializerError
    at com.cyb.mem.test.Test.main(Test.java:10)
Caused by: java.lang.IllegalStateException: Instrumentation is not setup properly. You have to pass -javaagent:path/to/object-explorer.jar to the java interpreter
    at com.cyb.mem.InstrumentationGrabber.checkSetup(InstrumentationGrabber.java:16)
    at com.cyb.mem.InstrumentationGrabber.instrumentation(InstrumentationGrabber.java:22)
    at com.cyb.mem.MemoryMeasurer.<clinit>(MemoryMeasurer.java:7)
    ... 1 more

**Comment by shaoshuaig** [comment]
i meet too, did you solve this problem?

**Comment by tungmeo** [comment]
Hi, I meet this and I've solved.
How do you run your java program, in an IDE or command line?
